#!/usr/bin/env bash
#
# Regenerates the sync-status block in FORK_CHANGES.md.
#
# Usage:
#   scripts/update-fork-changes.sh            # auto-detect newest fork-sync merge
#   scripts/update-fork-changes.sh <ref>      # use a specific sync merge commit
#
# Env:
#   FORK_CHANGES_BRANCH   branch to measure divergence against (default: origin/master)
#
# Works entirely from local git history; no network access to upstream is required.
# The upstream tip is the second parent of the GitHub "Sync fork" merge commit.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
DOC="$REPO_ROOT/FORK_CHANGES.md"
BRANCH="${FORK_CHANGES_BRANCH:-origin/master}"
START_MARKER='<!-- SYNC-STATUS:START -->'
END_MARKER='<!-- SYNC-STATUS:END -->'

die() {
  echo "error: $*" >&2
  exit 1
}

[ -f "$DOC" ] || die "$DOC not found"
grep -qF "$START_MARKER" "$DOC" || die "missing $START_MARKER in $DOC"
grep -qF "$END_MARKER" "$DOC" || die "missing $END_MARKER in $DOC"
git rev-parse --verify --quiet "$BRANCH" >/dev/null || die "branch '$BRANCH' not found (try: git fetch origin)"

# Locate the sync merge. Matches only GitHub "Sync fork" merges
# ("Merge branch 'advplyr:master' into master"), NOT upstream's own PR merges
# ("Merge pull request #123 from advplyr/some-branch"), which also contain "advplyr".
SYNC="${1:-}"
if [ -z "$SYNC" ]; then
  SYNC="$(git log --merges --format='%H %s' "$BRANCH" |
    grep -E "Merge branch 'advplyr:[^']+' into " |
    head -1 | cut -d' ' -f1 || true)"
  [ -n "$SYNC" ] || die "no fork-sync merge found on $BRANCH; pass one explicitly"
fi

SYNC="$(git rev-parse --verify --quiet "${SYNC}^{commit}" 2>/dev/null)" || die "invalid ref: ${1:-$SYNC}"
[ "$(git rev-list --parents -n1 "$SYNC" | wc -w)" -ge 3 ] || die "$(git rev-parse --short "$SYNC") is not a merge commit"

UPSTREAM="$(git rev-parse "${SYNC}^2")"

SYNC_DATE="$(git log -1 --format=%cs "$SYNC")"
SYNC_SHORT="$(git rev-parse --short "$SYNC")"
UPSTREAM_SHORT="$(git rev-parse --short "$UPSTREAM")"
UPSTREAM_SUBJECT="$(git log -1 --format=%s "$UPSTREAM")"
VERSION="$(git show "$BRANCH:package.json" | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
COMMIT_COUNT="$(git log --oneline --no-merges "$UPSTREAM..$BRANCH" | wc -l | tr -d ' ')"
DIVERGENCE="$(git diff --shortstat "$UPSTREAM...$BRANCH" | sed 's/^[[:space:]]*//')"
[ -n "$DIVERGENCE" ] || DIVERGENCE="no differences"

BLOCK="<!-- Generated by scripts/update-fork-changes.sh - do not edit by hand. -->

- **Last synced with upstream:** ${SYNC_DATE}
- **Upstream commit at sync:** \`${UPSTREAM_SHORT}\` — ${UPSTREAM_SUBJECT}
- **Sync merge commit:** \`${SYNC_SHORT}\`
- **Version:** ${VERSION}
- **Fork-only commits on \`${BRANCH}\`:** ${COMMIT_COUNT}
- **Net divergence:** ${DIVERGENCE}
"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
awk -v block="$BLOCK" -v start="$START_MARKER" -v end="$END_MARKER" '
  index($0, start) { print; print block; skipping = 1; next }
  index($0, end)   { skipping = 0 }
  !skipping        { print }
' "$DOC" >"$TMP"

[ -s "$TMP" ] || die "generated an empty document; aborting"
cat "$TMP" >"$DOC"

echo "Updated sync-status block in FORK_CHANGES.md:"
echo "  synced:     ${SYNC_DATE} (merge ${SYNC_SHORT})"
echo "  upstream:   ${UPSTREAM_SHORT} ${UPSTREAM_SUBJECT}"
echo "  version:    ${VERSION}"
echo "  fork-only:  ${COMMIT_COUNT} commits"
echo "  divergence: ${DIVERGENCE}"

# Keep formatting consistent with .prettierrc. Prettier is not a devDependency,
# so this is best-effort and never fails the run.
if npx --no-install prettier --write "$DOC" >/dev/null 2>&1; then
  echo "  formatted with prettier"
else
  echo "  note: prettier not run (not installed); run 'npx prettier --write FORK_CHANGES.md' if needed"
fi
